common:
  img_topic: "/trigger_cam/image_raw"
  lid_topic: "/ouster/points"
  imu_topic: "/ouster/imu"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  #extrinsic_T represents the translation of LiDAR frame w.r.t. IMU frame.
  #extrinsic_R represents the rotation matrix of LiDAR frame w.r.t. IMU frame.
  extrinsic_T: [ -0.033950, -0.000763, -0.078841 ]
  extrinsic_R: [  0.999993, -0.003628, -0.000450,
                  0.003629,  0.999991,  0.002080,
                  0.000442, -0.002081,  0.999998 ]
  # NTU_VIRAL
  Rcl: [ 0.015174, -0.999845, -0.008963,
        -0.000064,  0.008963, -0.999960,
         0.999885,  0.015174,  0.000072 ]
  Pcl: [ 0.011138, -0.013729, -0.001933 ]

time_offset:
  lidar_time_offset: 0.0
  imu_time_offset: 0.0
  img_time_offset: -0.2
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 10
  filter_size_surf: 0.2
  lidar_type: 3 # Ouster
  scan_line: 128
  blind: 1.0

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 3
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.5 # 0.2
  gyr_cov: 0.3 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.01
  min_eigen_value: 0.0025 # 0.0025
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "eee_01"
  pose_output_en: true

pcd_save:
  pcd_save_en: false
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.